
#ifndef PATENT_DISAMBIGUATION_H
#define PATENT_DISAMBIGUATION_H

#include "typedefs.h"

#define STRINGIZE_DETAIL(x) #x
#define STRINGIZE(x) STRINGIZE_DETAIL(x)


#endif /* PATENT_DISAMBIGUATION_H */
